## Project-wide Gradle settings.
APP_VERSION_CODE=1000
APP_VERSION_NAME=1.0.0
APP_PACKAGE=org.nayagram.platform
IS_PRIVATE=false

# Keystore signing configuration for Open-Source Builds
# For local builds, set your own passwords or leave empty for debug signing
RELEASE_KEY_PASSWORD=
RELEASE_KEY_ALIAS=
RELEASE_STORE_PASSWORD=

org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=512m -Djdk.tls.client.cipherSuites=TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA -Dhttps.cipherSuites=TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=false
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
