## Project-wide Gradle settings.
APP_VERSION_CODE=1
APP_VERSION_NAME=1.0.0
APP_PACKAGE=org.nayagram.platform
IS_PRIVATE=false

# Keystore signing configuration for Open-Source Builds
# For local builds, set your own passwords or leave empty for debug signing
RELEASE_KEY_PASSWORD=NayaGram@2026&TGPremik
RELEASE_KEY_ALIAS=payagrampro_key
RELEASE_STORE_PASSWORD=NayaGram@2026&TGPremik

org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=512m
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=false
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
android.enableR8.fullMode=true
android.r8.optimizedResourceShrinking=true
android.enableResourceOptimizations=true
org.gradle.tooling.parallel=true
